import type { Metadata } from "next";
import "./globals.css";
import Loading from "@/components/Loading";
import Delay from "@/components/Delay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="h-screen py-12 px-20 bg-[#F8F8F8]"
      >
        <Loading />
        <Delay children={children} />
        {/* {children} */}
      </body>
    </html>
  );
}
